apiVersion: v1
kind: Service
metadata:
  name: experiment-api-service
spec:
  type: NodePort
  selector:
    app: experiment-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
